services:
  mariadb:
    image: docker.io/library/mariadb:11.8.5
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: database
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpassword
