// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Instance struct {
	Vmid         uint32
	UserID       string
	TemplateVmid uint32
	IpAddress    sql.NullString
	CreatedAt    sql.NullTime
}

type VmTemplate struct {
	Vmid uint32
	Name string
}
