// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getInstanceByUserID = `-- name: GetInstanceByUserID :many
SELECT vmid, user_id, template_vmid, ip_address, created_at FROM instances WHERE user_id = ?
`

func (q *Queries) GetInstanceByUserID(ctx context.Context, userID string) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, getInstanceByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.Vmid,
			&i.UserID,
			&i.TemplateVmid,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
